# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Michael Horowitz"
#subtitle: "A chapter from my life"
author:  "Michael Horowitz"
header:
 title: "Photography"
 subtitle: "by Michael Horowitz"
footer:
# name: "Hello World! 👋'"
 bio: "This is my website to show my wildlife photography. I'm interested in primates and squirrels in particular, but I love all animals."

email_intro: "Email me at "
email: "me@michaelhorowitz.photo"
# bio: "I’m a software developer who writes. And 3D print. And photograph. Basically, following my curiosity and trying to find my purpose on this beautiful big blue ball. Learn more at: https://swiftlysingh.com"
#social_urls:
#  instagram: "https://www.instagram.com/pushpinderpalsingh_/"
#  twitter: "https://twitter.com/pushpinderpal_"

exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
